config/routes.rb
Cmall::Application.routes.draw do
     resources :products
     resources :brands
     resources :categories
     resources :messages
		 
		 resources :xiangmuzhaoshangs
		 resources :zhaopins
		 resources :qiugous
		 resources :huiyihuizhans
		 
  get "images/upload"
  get "images/image_list"
  
  get "hello/index"

   namespace :admin do
     resources :products
     resources :brands
     resources :categories
     resources :messages
   end
  

   root :to => 'hello#index'

end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :category, :content_id, :title, :content

  def content=(content)
    self.content_id = ProductContent.create({:content=>content}).id
  end

  def content
    content = ProductContent.find_by_id(self.content_id)
    content ? content.content : nil
  end
end

app/controllers/admin/messages_controller.rb
class Admin::MessagesController < AdminController
  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(params[:message])

    respond_to do |format|
      if @message.save
        format.html { redirect_to admin_messages_url, notice: 'Message was successfully created.' }
        format.json { render json: @message, status: :created, location: @message }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.json
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to admin_messages_url, notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to admin_messages_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(params[:message])

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render json: @message, status: :created, location: @message }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.json
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/messages_helper.rb
#encoding: utf-8
module MessagesHelper
  def options_for_message
    [["项目招商",'xiangmuzhaoshang'],['会议会展','huiyihuizhan'],["最新求购",'qiugou'],["企业招聘",'qiyezhaopin']]
  end
end

app/views/admin/messages/_form.html.erb
<%= form_for([:admin, @message]) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
      <%= f.select :category,options_for_select(options_for_message) %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.kindeditor :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', admin_messages_path %>

app/views/admin/messages/index.html.erb
<h1>Listing messages</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Category</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @messages.each do |message| %>
  <tr>
    <td><%= message.title %></td>
    <td><%= category_message(message.category) %></td>
    <td><%= message.content %></td>
    <td><%= link_to 'Show', message %></td>
    <td><%= link_to 'Edit', edit_admin_message_path(message) %></td>
    <td><%= link_to 'Destroy', admin_message_path(message), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Message', new_admin_message_path %>

app/views/admin/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_messages_path %>

app/views/admin/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @message.title %>
</p>

<p>
  <b>Category:</b>
  <%= @message.category %>
</p>

<p>
  <b>Content:</b>
  <%= @message.content_id %>
</p>


<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>