config/routes.rb
Cmall::Application.routes.draw do
     resources :products
     resources :brands
     resources :categories
     resources :messages
		 
		 resources :xiangmuzhaoshangs
		 resources :zhaopins
		 resources :qiugous
		 resources :huiyihuizhans
		 
  get "images/upload"
  get "images/image_list"
  
  get "hello/index"

   namespace :admin do
     resources :products
     resources :brands
     resources :categories
     resources :messages
   end
  

   root :to => 'hello#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :product_content_id, :max_price, :min_price, :price, :title,:brand_id,:category_id,:product_content, :image_id, :image
  belongs_to  :product_content
  belongs_to  :image


  def product_content=(content)
    self.content_id = ProductContent.create({:content=>content}).id
  end

  def image=(file)
      image_temp = Image.create(:data => file)
      self.image_id = image_temp.id
  end
  
  def product_content
    content = ProductContent.find_by_id(self.content_id)
    content ? content.content : nil
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_products_url, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to admin_products_url, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to admin_products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def get_category_select
    Category.where(:category_id =>0).inject({}) do |y,item|
      y[item.name] = item.child_categories.map{|x| [x.name, x.id.to_s]}
      y
    end
    
  end
end

app/views/admin/products/_form.html.erb
<%= form_for([:admin,  @product],:html=>{:multipart=>true}) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

<div class="field">
      <%= f.label :brand %><br />
    <%= f.select :brand_id, Brand.all.map{|x| [x.name, x.id]} %>
</div>
<div class="field">
      <%= f.label :category_id %><br />
    <%= f.select :category_id, grouped_options_for_select(get_category_select) %>
</div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :min_price %><br />
    <%= f.text_field :min_price %>
  </div>
  <div class="field">
    <%= f.label :max_price %><br />
    <%= f.text_field :max_price %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :product_content%><br />
    <%= f.kindeditor :product_content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', admin_products_path %>

app/views/admin/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Price</th>
    <th>Min price</th>
    <th>Max price</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.title %></td>
    <td><%= product.price %></td>
    <td><%= product.min_price %></td>
    <td><%= product.max_price %></td>
    <td><%= product.content_id %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_admin_product_path(product) %></td>
    <td><%= link_to 'Destroy', admin_product_path(product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_admin_product_path %>

app/views/admin/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_products_path %>

app/views/admin/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @product.title %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>

<p>
  <b>Min price:</b>
  <%= @product.min_price %>
</p>

<p>
  <b>Max price:</b>
  <%= @product.max_price %>
</p>

<p>
  <b>Content:</b>
  <%= @product.content_id %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>